{{- if .Values.storageClasses.gp3Ext4.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-ext4

provisioner: ebs.csi.aws.com

parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp3
  encrypted: "true"

reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{- end }}
