apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
data:
  index.html: |
    <!doctype html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <title>Hello World</title>
      </head>
      <body>
        <h1>{{ .Values.message }}</h1>
        <p>Environment: {{ .Values.global.environment }}</p>
        <p>Cluster: {{ .Values.global.clusterName }}</p>
        <p>Release: {{ .Release.Name }}</p>
      </body>
    </html>
