{{- $root := . -}}
{{- range $eksNamespace, $cfg := $root.Values.secretConsumers }}
{{- if ($cfg.enabled | default false) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $root.Values.serviceAccount.name | default "vault-auth" | quote }}
  namespace: {{ $eksNamespace | quote }}
  labels:
    app.kubernetes.io/name: vault-secrets-operator
    app.kubernetes.io/component: vault-auth-serviceaccount
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: platform
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
{{- end }}
{{- end }}
