apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-required-secrets
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: pre-sync-sa
      restartPolicy: Never

      containers:
      - name: check-secrets
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
{{- range .Values.nginxIngress.requiredSecrets }}
          echo "Waiting for {{ . }}..."

          until kubectl get secret {{ . }} -n nginx-ingress >/dev/null 2>&1
          do
            echo "{{ . }} not found yet"
            sleep 5
          done

          echo "{{ . }} found"
{{- end }}

          echo "All required secrets are available"
