clusterName: ""
repoURL: https://github.com/YOUR_ORG/multi-cluster-multi-apps-poc.git
targetRevision: main
gitopsNamespace: harness-gitops

applicationSet:
  requeueAfterSeconds: 60
  preserveResourcesOnDeletion: false
