app:
  name: nginx-ingress
  namespace: nginx-ingress
  releaseName: nginx-ingress
  chartPath: eks/apps/nginx-ingress
  valuesFile: nginx-ingress.yaml

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
