namespaces:
  monitoring: {}

global:
  environment: prd

vault:
  address: https://hcv.fiscloudservices.com

argocd:
  syncWaves:
    namespaces: "-30"
    vaultSecretsOperator: "-20"
    platformSecrets: "-10"
    applications: "0"

serviceAccount:
  name: vault-auth

artifactory:
  dockerRegistry: ptp-docker-snapshot-local.docker.fis.dev
  dockerUsername: svcacct-ptp-caas-snapshot
  dockerPasswordKey: token

nginxIngress:
  requiredSecrets:
    - artifactory-regcred
    - nginx-default-tls

environmentApps:
  - namespaces
  - storageclass
  - nginx-ingress
  - cluster-autoscaler
