apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-demo.fullname" . }}
data:
  index.html: |
    <html>
    <body>
    <h1>{{ .Values.message }}</h1>
    <p>Release: {{ .Release.Name }}</p>
    <p>Namespace: {{ .Release.Namespace }}</p>
    </body>
    </html>