apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-demo.fullname" . }}

spec:
  selector:
    app: {{ include "nginx-demo.name" . }}

  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}

  type: {{ .Values.service.type }}